manager/urls.py
from django.urls import path

from manager.views import (
    index,
    my_tasks,
    ProjectListView,
    ProjectDetailView,
    ProjectCreateView,
    ProjectUpdateView,
    ProjectDeleteView,
    TagListView,
    TagDetailView,
    TagCreateView,
    TagUpdateView,
    TagDeleteView,
    TaskTypeListView,
    TaskTypeDetailView,
    TaskTypeCreateView,
    TaskTypeUpdateView,
    TaskTypeDeleteView,
    TeamListView,
    TeamDetailView,
    TeamCreateView,
    TeamUpdateView,
    TeamDeleteView,
    PositionListView,
    PositionDetailView,
    PositionCreateView,
    PositionUpdateView,
    PositionDeleteView,
    WorkerListView,
    WorkerDetailView,
    WorkerCreateView,
    WorkerUpdateView,
    WorkerDeleteView,
    TaskListView,
    TaskCreateView,
    TaskUpdateView,
    TaskDetailView,
    TaskDeleteView,
)

urlpatterns = [
    path("", index, name="index"),
    path("my-tasks/", my_tasks, name="my-tasks"),
    path("projects/", ProjectListView.as_view(), name="project-list"),
    path("projects/create/", ProjectCreateView.as_view(), name="project-create"),
    path("projects/<int:pk>/", ProjectDetailView.as_view(), name="project-detail"),
    path(
        "projects/<int:pk>/update/", ProjectUpdateView.as_view(), name="project-update"
    ),
    path(
        "projects/<int:pk>/delete/", ProjectDeleteView.as_view(), name="project-delete"
    ),
    path(
        "projects/<int:pk>/tasks/",
        TaskListView.as_view(),
        name="task-list",
    ),
    path(
        "projects/<int:pk>/tasks/create/",
        TaskCreateView.as_view(),
        name="task-create",
    ),
    path(
        "tasks/<int:pk>/",
        TaskDetailView.as_view(),
        name="task-detail",
    ),
    path(
        "tasks/<int:pk>/update/",
        TaskUpdateView.as_view(),
        name="task-update",
    ),
    path(
        "tasks/<int:pk>/delete/",
        TaskDeleteView.as_view(),
        name="task-delete",
    ),
    path("projects/<int:pk>/tags/", TagListView.as_view(), name="tag-list"),
    path("projects/<int:pk>/tags/create/", TagCreateView.as_view(), name="tag-create"),
    path("tags/<int:pk>/", TagDetailView.as_view(), name="tag-detail"),
    path(
        "tags/<int:pk>/update/",
        TagUpdateView.as_view(),
        name="tag-update",
    ),
    path(
        "tags/<int:pk>/delete/",
        TagDeleteView.as_view(),
        name="tag-delete",
    ),
    path(
        "projects/<int:pk>/task-types/",
        TaskTypeListView.as_view(),
        name="task-type-list",
    ),
    path(
        "projects/<int:pk>/task-types/create/",
        TaskTypeCreateView.as_view(),
        name="task-type-create",
    ),
    path(
        "task-types/<int:pk>/",
        TaskTypeDetailView.as_view(),
        name="task-type-detail",
    ),
    path(
        "task-types/<int:pk>/update/",
        TaskTypeUpdateView.as_view(),
        name="task-type-update",
    ),
    path(
        "task-types/<int:pk>/delete/",
        TaskTypeDeleteView.as_view(),
        name="task-type-delete",
    ),
    path("teams/", TeamListView.as_view(), name="team-list"),
    path("teams/<int:pk>/", TeamDetailView.as_view(), name="team-detail"),
    path("teams/create/", TeamCreateView.as_view(), name="team-create"),
    path("teams/<int:pk>/update/", TeamUpdateView.as_view(), name="team-update"),
    path("teams/<int:pk>/delete/", TeamDeleteView.as_view(), name="team-delete"),
    path("teams/<int:pk>/positions/", PositionListView.as_view(), name="position-list"),
    path(
        "teams/<int:pk>/positions/create/",
        PositionCreateView.as_view(),
        name="position-create",
    ),
    path(
        "positions/<int:pk>/",
        PositionDetailView.as_view(),
        name="position-detail",
    ),
    path(
        "positions/<int:pk>/update/",
        PositionUpdateView.as_view(),
        name="position-update",
    ),
    path(
        "positions/<int:pk>/delete/",
        PositionDeleteView.as_view(),
        name="position-delete",
    ),
    path("workers/", WorkerListView.as_view(), name="worker-list"),
    path("workers/<int:pk>/", WorkerDetailView.as_view(), name="worker-detail"),
    path("workers/create/", WorkerCreateView.as_view(), name="worker-create"),
    path("workers/<int:pk>/update/", WorkerUpdateView.as_view(), name="worker-update"),
    path("workers/<int:pk>/delete/", WorkerDeleteView.as_view(), name="worker-delete"),
]

app_name = "manager"

task_manager/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from manager.views import profile

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("manager.urls", namespace="manager")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("accounts/profile", profile, name="profile"),
    path("__debug__/", include("debug_toolbar.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

manager/models/position.py
from django.db import models


class Position(models.Model):
    name = models.CharField(max_length=63)

    team = models.ForeignKey(to="Team", on_delete=models.CASCADE)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["name"]
        index_together = ["name", "team"]
        unique_together = ["name", "team"]

    def __str__(self) -> str:
        return f"Position: {self.name}"

manager/models/project.py
from django.db import models


class Project(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField(max_length=1000, null=True, blank=True)
    start_date = models.DateField()
    budget = models.IntegerField()

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["name"]
        indexes = [models.Index(fields=["name"])]

    def __str__(self) -> str:
        date = self.start_date.strftime("%Y-%m-%d")

        return f"Project: {self.name} (budget: {self.budget}, start date: {date})"

manager/models/tag.py
from django.db import models


class Tag(models.Model):
    name = models.CharField(max_length=63)

    project = models.ForeignKey(to="Project", on_delete=models.CASCADE)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["name"]
        index_together = ["name", "project"]
        unique_together = ["name", "project"]

    def __str__(self) -> str:
        return f"Tag: {self.name}"

manager/models/task.py
from django.db import models

from task_manager.settings import AUTH_USER_MODEL

PRIORITIES = (
    ("highest", "Highest"),
    ("high", "High"),
    ("medium", "Medium"),
    ("low", "Low"),
    ("lowest", "Lowest"),
)


class Task(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField(max_length=1000, null=True, blank=True)
    deadline = models.DateField()
    is_completed = models.BooleanField(default=False)
    priority = models.CharField(max_length=7, choices=PRIORITIES)

    task_type = models.ForeignKey(
        to="TaskType", on_delete=models.SET_NULL, null=True, blank=True
    )
    reporter = models.ForeignKey(
        to=AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, blank=True
    )
    project = models.ForeignKey(
        to="Project", on_delete=models.CASCADE, related_name="tasks"
    )

    assignees = models.ManyToManyField(
        to=AUTH_USER_MODEL, related_name="tasks", blank=True
    )
    tags = models.ManyToManyField(to="Tag", related_name="tasks", blank=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["-updated_at"]

    def __str__(self) -> str:
        date = self.deadline.strftime("%Y-%m-%d")

        return f"Task: {self.name} (priority: {self.priority}, deadline: {date})"

manager/models/task_type.py
from django.db import models


class TaskType(models.Model):
    name = models.CharField(max_length=63)

    project = models.ForeignKey(to="Project", on_delete=models.CASCADE)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["name"]
        index_together = ["name", "project"]
        unique_together = ["name", "project"]

    def __str__(self) -> str:
        return f"Task type: {self.name}"

manager/models/team.py
from django.db import models

from task_manager.settings import AUTH_USER_MODEL


class Team(models.Model):
    name = models.CharField(max_length=255)

    team_lead = models.ForeignKey(
        to=AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        related_name="team_lead",
        null=True,
        blank=True,
    )
    projects = models.ManyToManyField(to="Project", related_name="teams", blank=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self) -> str:
        return f"Team: {self.name}"

manager/models/worker.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class Worker(AbstractUser):
    position = models.ForeignKey(
        to="Position", on_delete=models.SET_NULL, null=True, blank=True
    )
    team = models.ForeignKey(
        to="Team",
        on_delete=models.SET_NULL,
        related_name="workers",
        null=True,
        blank=True,
    )

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = "worker"
        verbose_name_plural = "workers"

    def __str__(self) -> str:
        position = self.position.name if self.position else "No position"

        return (
            f"Worker: {self.username} ({self.first_name} {self.last_name}), {position}"
        )

manager/forms/positin_form.py
from django import forms
from manager.models import Position


class PositionForm(forms.ModelForm):
    class Meta:
        model = Position
        fields = ("name",)

manager/forms/project_form.py
from datetime import datetime, date

from django import forms
from django.core.exceptions import ValidationError

from manager.models import Project


class ProjectFrom(forms.ModelForm):
    start_date = forms.DateField(widget=forms.DateInput(attrs={"type": "date"}))

    class Meta:
        model = Project
        fields = "__all__"

    def clean_start_date(self) -> datetime:
        project_start_date = self.cleaned_data["start_date"]

        if project_start_date < date.today():
            raise ValidationError("Please, select date in future")

        return project_start_date

manager/forms/tag_form.py
from django import forms

from manager.models import Tag


class TagForm(forms.ModelForm):
    class Meta:
        model = Tag
        fields = ("name",)

manager/forms/task_form.py
from datetime import datetime, date

from django import forms
from django.contrib.auth import get_user_model
from django.core.exceptions import ValidationError

from manager.models import Task, Tag


class TaskForm(forms.ModelForm):
    deadline = forms.DateField(widget=forms.DateInput(attrs={"type": "date"}))
    assignees = forms.ModelMultipleChoiceField(
        queryset=get_user_model().objects.all(),
        widget=forms.CheckboxSelectMultiple,
    )
    tags = forms.ModelMultipleChoiceField(
        queryset=Tag.objects.all(),
        widget=forms.CheckboxSelectMultiple,
    )

    class Meta:
        model = Task
        fields = (
            "name",
            "description",
            "deadline",
            "priority",
            "task_type",
            "reporter",
            "assignees",
            "tags",
        )

    def clean_deadline(self) -> datetime:
        task_deadline = self.cleaned_data["deadline"]

        if task_deadline < date.today():
            raise ValidationError("Please, select date in future")

        return task_deadline

manager/forms/task_type_form.py
from django import forms

from manager.models import TaskType


class TaskTypeForm(forms.ModelForm):
    class Meta:
        model = TaskType
        fields = ("name",)

manager/forms/team_form.py
from django import forms

from manager.models import Team, Project


class TeamForm(forms.ModelForm):
    projects = forms.ModelMultipleChoiceField(
        queryset=Project.objects.all(),
        widget=forms.CheckboxSelectMultiple,
    )

    class Meta:
        model = Team
        fields = ("name", "team_lead", "projects")

manager/forms/worker_form.py
from django.contrib.auth.forms import UserCreationForm

from manager.models import Worker


class WorkerForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = Worker
        fields = UserCreationForm.Meta.fields + (
            "first_name",
            "last_name",
            "team",
            "position",
        )

manager/views/index.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render

from manager.services import get_projects_with_tasks


@login_required
def index(request: HttpRequest) -> HttpResponse:
    project_name = request.GET.get("project-name")

    projects = get_projects_with_tasks(project_name)

    paginator = Paginator(projects, 5)
    page_number = request.GET.get("page")

    try:
        projects = paginator.page(page_number)
    except PageNotAnInteger:
        projects = paginator.page(1)
    except EmptyPage:
        projects = paginator.page(paginator.num_pages)

    context = {
        "segment": ["index", "search"],
        "page_obj": projects,
        "is_paginated": paginator.num_pages > 1,
        "search_value": project_name if project_name else "",
        "search_name": "project-name",
        "search_placeholder": "Search projects",
        "user": request.user,
    }

    return render(request=request, template_name="manager/index.html", context=context)

manager/views/my_tasks.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render

from manager.services import get_user_tasks


@login_required
def my_tasks(request: HttpRequest) -> HttpResponse:
    task_name = request.GET.get("task-name")
    is_completed = (
        request.GET.get("is_completed") == "True"
        if request.GET.get("is_completed")
        else None
    )

    tasks = get_user_tasks(user=request.user, name=task_name, is_completed=is_completed)

    paginator = Paginator(tasks, 10)
    page_number = request.GET.get("page")

    try:
        tasks = paginator.page(page_number)
    except PageNotAnInteger:
        tasks = paginator.page(1)
    except EmptyPage:
        tasks = paginator.page(paginator.num_pages)

    context = {
        "segment": ["search"],
        "search_name": "task-name",
        "search_placeholder": "Search tasks",
        "is_completed": is_completed if isinstance(is_completed, bool) else None,
        "search_value": task_name if task_name else "",
        "page_obj": tasks,
        "is_paginated": paginator.num_pages > 1,
    }

    return render(
        request=request, template_name="manager/my_tasks.html", context=context
    )

manager/views/profile.py
from django.contrib.auth.decorators import login_required
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render

from manager.services import update_user


@login_required
def profile(request: HttpRequest) -> HttpResponse:
    user = request.user

    if request.method == "POST":
        user = update_user(
            user_id=request.user.id,
            email=request.POST.get("email"),
            username=request.POST.get("username"),
            first_name=request.POST.get("first_name"),
            last_name=request.POST.get("last_name"),
        )

    context = {
        "user": user,
    }

    return render(
        request=request, template_name="manager/profile.html", context=context
    )

manager/views/project_list.py
from django.views import generic

from manager.models import Project


class ProjectListView(generic.ListView):
    model = Project
    context_object_name = "project_list"

templates/manager/my_tasks.html
{% extends 'layouts/base.html' %}
{% load query_transform %}
{% load static %}

{% block content %}
  <div class="row">
    <div class="col-xl-12">
      <div class="btn-group mb-4" role="group" aria-label="Basic outlined example">
        <a
            class="btn btn-outline-primary {% if is_completed is None %}active{% endif %}"
            href="?{% query_transform request is_completed="" %}"
        >
          All
        </a>

        <a
            class="btn btn-outline-primary {% if is_completed is True %}active{% endif %}"
            href="?{% query_transform request is_completed=True %}"
        >
          Completed
        </a>

        <a
            class="btn btn-outline-primary {% if is_completed is False %}active{% endif %}"
            href="?{% query_transform request is_completed=False %}"
        >
          Not completed
        </a>
      </div>

      <div class="card Recent-Users">
        <div class="card-block px-0 py-3">
          <div class="table-responsive">
            {% if page_obj %}
              <table class="table table-hover">
                <thead>
                <tr>
                  <td>Project</td>
                  <td>Task</td>
                  <td>Updated at</td>
                  <td>Completed</td>
                  <td>Actions</td>
                </tr>
                </thead>

                <tbody>
                {% for task in page_obj %}
                  <tr class="unread">
                    <td>
                      <h6 class="m-0">
                        {{ task.project.name }}
                      </h6>
                    </td>

                    <td>
                      <h6 class="mb-1">{{ task.name }}</h6>
                    </td>

                    <td>
                      <h6 class="text-muted">{{ task.updated_at }}</h6>
                    </td>

                    <td>
                      <h6 class="text-muted">
                        {% if task.is_completed %}
                          <i class="fas fa-circle text-c-green f-10 m-r-15"></i>
                          Completed
                        {% else %}
                          <i class="fas fa-circle text-c-red f-10 m-r-15"></i>
                          Not completed
                        {% endif %}
                      </h6>
                    </td>

                    <td>
                      <a
                          href="{% url "manager:task-detail" pk=task.pk %}"
                          class="label theme-bg text-white f-12"
                      >Details</a>

                      <a
                          href="{% url "manager:task-update" pk=task.pk %}"
                          class="label theme-bg text-white f-12"
                      >Edit</a>

                      <a
                          href="{% url "manager:task-delete" pk=task.pk %}"
                          class="label theme-bg2 text-white f-12"
                      >Delete</a>
                    </td>
                  </tr>
                {% endfor %}
                </tbody>
              </table>
            {% else %}
              <h3 class="text-center">No tasks</h3>
            {% endif %}
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

templates/manager/position_detail.html
{% extends 'layouts/base.html' %}
{% load humanize %}
{% load static %}

{% block content %}
  <div class="row">
    <div class="col-xl-12">
      <div class="card Recent-Users p-3">
        <h3 class="text-center">{{ position.name }}</h3>

        <h5>Last update date: {{ position.updated_at }}</h5>
        <h5 class="mb-5">Related team: {{ position.team.name }}</h5>
      </div>

      <a href="{% url "manager:position-list" pk=position.team.pk %}" class="btn btn-danger">Back</a>
    </div>
  </div>
{% endblock content %}

templates/manager/position_list.html
{% extends 'layouts/base.html' %}
{% load static %}

{% block content %}
  <div class="row">
    <div class="col-xl-12">
      <h2 class="mb-4">{{ team.name }} positions</h2>
      <a href="{% url "manager:position-create" pk=team.id %}" class="btn btn-primary mb-3">Add position</a>

      <div class="card Recent-Users">
        <div class="card-block px-0 py-3">
          <div class="table-responsive">
            {% if position_list %}
              <table class="table table-hover">
                <thead>
                <tr>
                  <td>Name</td>
                  <td>Team</td>
                  <td>Updated at</td>
                  <td>Actions</td>
                </tr>
                </thead>

                <tbody>
                {% for position in position_list %}
                  <tr class="unread">
                    <td>
                      <h6 class="m-0">
                        {{ position.name }}
                      </h6>
                    </td>

                    <td>
                      <h6 class="mb-1">{{ position.team.name }}</h6>
                    </td>

                    <td>
                      <h6 class="text-muted">{{ position.updated_at }}</h6>
                    </td>

                    <td>
                      <a
                          href="{% url "manager:position-detail" pk=position.pk %}"
                          class="label theme-bg text-white f-12"
                      >Details</a>

                      <a
                          href="{% url "manager:position-update" pk=position.pk %}"
                          class="label theme-bg text-white f-12"
                      >Edit</a>

                      <a
                          href="{% url "manager:position-delete" pk=position.pk %}"
                          class="label theme-bg2 text-white f-12"
                      >Delete</a>
                    </td>
                  </tr>
                {% endfor %}
                </tbody>
              </table>
            {% else %}
              <h3 class="text-center">No positions</h3>
            {% endif %}
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

templates/manager/task_list.html
{% extends 'layouts/base.html' %}
{% load static %}

{% block content %}
  <div class="row">
    <div class="col-xl-12">
      <h2 class="mb-4">{{ project.name }} tasks</h2>
      <a href="{% url "manager:task-create" pk=project.pk %}" class="btn btn-primary mb-3">Add task</a>

      <div class="card Recent-Users">
        <div class="card-block px-0 py-3">
          <div class="table-responsive">
            {% if task_list %}
              <table class="table table-hover">
                <thead>
                <tr>
                  <td>Name</td>
                  <td>Deadline</td>
                  <td>Completed</td>
                  <td>Assignees</td>
                  <td>Actions</td>
                </tr>
                </thead>

                <tbody>
                {% for task in task_list %}
                  <tr class="unread">
                    <td>
                      <h6 class="m-0">
                        {{ task.name }}
                      </h6>
                    </td>

                    <td>
                      <h6 class="mb-1">{{ task.deadline }}</h6>
                    </td>

                    <td>
                      {% if task.is_completed %}
                        <i class="fas fa-circle text-c-green f-10 m-r-15"></i>
                        Completed
                      {% else %}
                        <i class="fas fa-circle text-c-red f-10 m-r-15"></i>
                        Not completed
                      {% endif %}
                    </td>

                    <td>
                      {% if task.assignees.all %}
                        {% for worker in task.assignees.all %}
                          <h6>{{ worker.username }}</h6>
                        {% endfor %}

                      {% else %}
                        <h6>No assignees yet</h6>
                      {% endif %}
                    </td>

                    <td>
                      <a
                          href="{% url "manager:task-detail" pk=task.pk %}"
                          class="label theme-bg text-white f-12"
                      >Details</a>

                      <a
                          href="{% url "manager:task-update" pk=task.pk %}"
                          class="label theme-bg text-white f-12"
                      >Edit</a>

                      <a
                          href="{% url "manager:task-delete" pk=task.pk %}"
                          class="label theme-bg2 text-white f-12"
                      >Delete</a>
                    </td>
                  </tr>
                {% endfor %}
                </tbody>
              </table>
            {% else %}
              <h3 class="text-center">No tasks</h3>
            {% endif %}
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

templates/manager/team_detail.html
{% extends 'layouts/base.html' %}
{% load humanize %}
{% load static %}

{% block content %}
  <div class="row">
    <div class="col-xl-12">
      <div class="card Recent-Users p-3">
        <h3 class="text-center">{{ team.name }}</h3>

        <h5>Team Lead: {{ team.team_lead.username }}</h5>
        <h5>
          Projects:
          {% for project in team.projects.all %}
            {% if forloop.last %}
              <span>{{ project.name }}</span>
            {% else %}
              <span>{{ project.name }},</span>
            {% endif %}
          {% endfor %}
        </h5>

        <div>
          <a href="{% url "manager:position-list" pk=team.pk %}" class="btn btn-outline-primary mt-5">Positions</a>
        </div>
      </div>

      <a href="{% url "manager:team-list" %}" class="btn btn-danger">Back</a>
    </div>
  </div>
{% endblock content %}

templates/manager/team_list.html
{% extends 'layouts/base.html' %}
{% load static %}

{% block content %}
  <div class="row">
    <div class="col-xl-12">
      <h2 class="mb-4">Teams</h2>
      <a href="{% url "manager:team-create" %}" class="btn btn-primary mb-3">Add team</a>

      <div class="card Recent-Users">
        <div class="card-block px-0 py-3">
          <div class="table-responsive">
            {% if team_list %}
              <table class="table table-hover">
                <thead>
                <tr>
                  <td>Name</td>
                  <td>Team Lead</td>
                  <td>Projects</td>
                  <td>Updated at</td>
                  <td>Actions</td>
                </tr>
                </thead>

                <tbody>
                {% for team in team_list %}
                  <tr class="unread">
                    <td>
                      <h6 class="m-0">
                        {{ team.name }}
                      </h6>
                    </td>

                    <td>
                      <h6 class="mb-1">{{ team.team_lead.name }}</h6>
                    </td>

                    <td>
                      {% if team.projects.all %}
                        {% for project in team.projects.all %}
                          <h6>{{ project.name }}</h6>
                        {% endfor %}

                      {% else %}
                        <h6>No projects yet</h6>
                      {% endif %}
                    </td>

                    <td>
                      <h6 class="text-muted">{{ team.updated_at }}</h6>
                    </td>

                    <td>
                      <a
                          href="{% url "manager:team-detail" pk=team.pk %}"
                          class="label theme-bg text-white f-12"
                      >Details</a>

                      <a
                          href="{% url "manager:team-update" pk=team.pk %}"
                          class="label theme-bg text-white f-12"
                      >Edit</a>

                      <a
                          href="{% url "manager:team-delete" pk=team.pk %}"
                          class="label theme-bg2 text-white f-12"
                      >Delete</a>
                    </td>
                  </tr>
                {% endfor %}
                </tbody>
              </table>
            {% else %}
              <h3 class="text-center">No teams</h3>
            {% endif %}
          </div>
        </div>
      </div>
    </div>
  </div>

{% endblock content %}

templates/manager/worker_list.html
{% extends 'layouts/base.html' %}
{% load static %}

{% block content %}
  <div class="row">
    <div class="col-xl-12">
      <h2 class="mb-4">Workers</h2>
      <a href="{% url "manager:worker-create" %}" class="btn btn-primary mb-3">Add worker</a>

      <div class="card Recent-Users">
        <div class="card-block px-0 py-3">
          <div class="table-responsive">
            {% if worker_list %}
              <table class="table table-hover">
                <thead>
                <tr>
                  <td>Username</td>
                  <td>First name</td>
                  <td>Last name</td>
                  <td>Position</td>
                  <td>Team</td>
                  <td>Actions</td>
                </tr>
                </thead>

                <tbody>
                {% for worker in worker_list %}
                  <tr class="unread">
                    <td>
                      <h6 class="m-0">
                        {{ worker.username }}
                      </h6>
                    </td>

                    <td>
                      <h6 class="mb-1">{{ worker.first_name }}</h6>
                    </td>

                    <td>
                      <h6 class="text-muted">{{ worker.last_name }}</h6>
                    </td>

                    <td>
                      <h6 class="text-muted">{{ worker.position.name }}</h6>
                    </td>

                    <td>
                      <h6 class="text-muted">{{ worker.team.name }}</h6>
                    </td>

                    <td>
                      <a
                          href="{% url "manager:worker-detail" pk=worker.pk %}"
                          class="label theme-bg text-white f-12"
                      >Details</a>

                      <a
                          href="{% url "manager:worker-update" pk=worker.pk %}"
                          class="label theme-bg text-white f-12"
                      >Edit</a>

                      <a
                          href="{% url "manager:worker-delete" pk=worker.pk %}"
                          class="label theme-bg2 text-white f-12"
                      >Delete</a>
                    </td>
                  </tr>
                {% endfor %}
                </tbody>
              </table>
            {% else %}
              <h3 class="text-center">No workers</h3>
            {% endif %}
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}