manager/urls.py
from django.urls import path

from manager.views import (
    index,
    my_tasks,
    ProjectListView,
    ProjectDetailView,
    ProjectCreateView,
    ProjectUpdateView,
    ProjectDeleteView,
    TagListView,
    TagDetailView,
    TagCreateView,
    TagUpdateView,
    TagDeleteView,
    TaskTypeListView,
    TaskTypeDetailView,
    TaskTypeCreateView,
    TaskTypeUpdateView,
    TaskTypeDeleteView,
    TeamListView,
    TeamDetailView,
    TeamCreateView,
    TeamUpdateView,
    TeamDeleteView,
    PositionListView,
    PositionDetailView,
    PositionCreateView,
    PositionUpdateView,
    PositionDeleteView,
    WorkerListView,
    WorkerDetailView,
    WorkerCreateView,
    WorkerUpdateView,
    WorkerDeleteView,
    TaskListView,
    TaskCreateView,
    TaskUpdateView,
    TaskDetailView,
    TaskDeleteView,
)

urlpatterns = [
    path("", index, name="index"),
    path("my-tasks/", my_tasks, name="my-tasks"),
    path("projects/", ProjectListView.as_view(), name="project-list"),
    path("projects/create/", ProjectCreateView.as_view(), name="project-create"),
    path("projects/<int:pk>/", ProjectDetailView.as_view(), name="project-detail"),
    path(
        "projects/<int:pk>/update/", ProjectUpdateView.as_view(), name="project-update"
    ),
    path(
        "projects/<int:pk>/delete/", ProjectDeleteView.as_view(), name="project-delete"
    ),
    path(
        "projects/<int:pk>/tasks/",
        TaskListView.as_view(),
        name="task-list",
    ),
    path(
        "projects/<int:pk>/tasks/create/",
        TaskCreateView.as_view(),
        name="task-create",
    ),
    path(
        "tasks/<int:pk>/",
        TaskDetailView.as_view(),
        name="task-detail",
    ),
    path(
        "tasks/<int:pk>/update/",
        TaskUpdateView.as_view(),
        name="task-update",
    ),
    path(
        "tasks/<int:pk>/delete/",
        TaskDeleteView.as_view(),
        name="task-delete",
    ),
    path("projects/<int:pk>/tags/", TagListView.as_view(), name="tag-list"),
    path("projects/<int:pk>/tags/create/", TagCreateView.as_view(), name="tag-create"),
    path("tags/<int:pk>/", TagDetailView.as_view(), name="tag-detail"),
    path(
        "tags/<int:pk>/update/",
        TagUpdateView.as_view(),
        name="tag-update",
    ),
    path(
        "tags/<int:pk>/delete/",
        TagDeleteView.as_view(),
        name="tag-delete",
    ),
    path(
        "projects/<int:pk>/task-types/",
        TaskTypeListView.as_view(),
        name="task-type-list",
    ),
    path(
        "projects/<int:pk>/task-types/create/",
        TaskTypeCreateView.as_view(),
        name="task-type-create",
    ),
    path(
        "task-types/<int:pk>/",
        TaskTypeDetailView.as_view(),
        name="task-type-detail",
    ),
    path(
        "task-types/<int:pk>/update/",
        TaskTypeUpdateView.as_view(),
        name="task-type-update",
    ),
    path(
        "task-types/<int:pk>/delete/",
        TaskTypeDeleteView.as_view(),
        name="task-type-delete",
    ),
    path("teams/", TeamListView.as_view(), name="team-list"),
    path("teams/<int:pk>/", TeamDetailView.as_view(), name="team-detail"),
    path("teams/create/", TeamCreateView.as_view(), name="team-create"),
    path("teams/<int:pk>/update/", TeamUpdateView.as_view(), name="team-update"),
    path("teams/<int:pk>/delete/", TeamDeleteView.as_view(), name="team-delete"),
    path("teams/<int:pk>/positions/", PositionListView.as_view(), name="position-list"),
    path(
        "teams/<int:pk>/positions/create/",
        PositionCreateView.as_view(),
        name="position-create",
    ),
    path(
        "positions/<int:pk>/",
        PositionDetailView.as_view(),
        name="position-detail",
    ),
    path(
        "positions/<int:pk>/update/",
        PositionUpdateView.as_view(),
        name="position-update",
    ),
    path(
        "positions/<int:pk>/delete/",
        PositionDeleteView.as_view(),
        name="position-delete",
    ),
    path("workers/", WorkerListView.as_view(), name="worker-list"),
    path("workers/<int:pk>/", WorkerDetailView.as_view(), name="worker-detail"),
    path("workers/create/", WorkerCreateView.as_view(), name="worker-create"),
    path("workers/<int:pk>/update/", WorkerUpdateView.as_view(), name="worker-update"),
    path("workers/<int:pk>/delete/", WorkerDeleteView.as_view(), name="worker-delete"),
]

app_name = "manager"

task_manager/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from manager.views import profile

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("manager.urls", namespace="manager")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("accounts/profile", profile, name="profile"),
    path("__debug__/", include("debug_toolbar.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/includes/head.html
{% load static %}
<title>Task Manager</title>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimal-ui">
<meta http-equiv="X-UA-Compatible" content="IE=edge"/>
<link rel="icon" href="{% static 'assets/images/favicon.svg' %}" type="image/x-icon">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
<link rel="stylesheet" href="{% static 'assets/fonts/fontawesome/css/fontawesome-all.min.css' %}">
<link rel="stylesheet" href="{% static 'assets/plugins/animation/css/animate.min.css' %}">
<link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
<link rel="stylesheet" href="{% static 'assets/css/dark.css' %}">
<script src="https://kit.fontawesome.com/a7c600f22c.js" crossorigin="anonymous"></script>

templates/includes/navigation.html
{% load static %}

<header class="navbar pcoded-header navbar-expand-lg navbar-light">
  <div class="m-header">
    <a class="mobile-menu" id="mobile-collapse1" href="javascript:">
      <span></span>
    </a>

    <a href="{% url 'manager:index' %}" class="b-brand">
      <i class="fa-solid fa-list-check" style="color: #63E6BE;"></i>

      <span class="b-title">Task Manager</span>
    </a>
  </div>

  <a class="mobile-menu" id="mobile-header" href="javascript:">
    <i class="feather icon-more-horizontal"></i>
  </a>

  <div class="collapse navbar-collapse">
    <ul class="navbar-nav mr-auto">
      {% if "search" in segment %}
        <li class="nav-item">
          <form method="get" action="">
            <div class="input-group mb-3">
              <input
                  type="text"
                  class="form-control"
                  placeholder="{{ search_placeholder }}"
                  name="{{ search_name }}"
                  value="{{ search_value }}"
              >

              <div class="input-group-append">
                <button class="btn btn-primary" type="submit">Search</button>
              </div>
            </div>
          </form>
        </li>
      {% endif %}
    </ul>

    <ul class="navbar-nav ml-auto">
      <li>
        <label>
          <i class="icon feather icon-sun" id="theme-indicator"></i>
          <input type="checkbox" id="theme-switch" class="d-none">
        </label>
      </li>

      <li>
        <div class="dropdown drp-user">
          <a href="javascript:" class="dropdown-toggle" data-toggle="dropdown">
            <i class="icon feather icon-settings"></i>
          </a>

          <div class="dropdown-menu dropdown-menu-right profile-notification">
            <div class="pro-head">
              <span>{{ user.first_name }} {{ user.last_name }}</span>

              <form method="post" action="{% url "logout" %}">
                {% csrf_token %}

                <button type="submit" class="dud-logout btn btn-link" title="Logout">
                  <i class="feather icon-log-out"></i>
                </button>
              </form>
            </div>

            <ul class="pro-body">
              <li>
                <a href="{% url "profile" %}" class="dropdown-item">
                  <i class="feather icon-user"></i>
                  Profile
                </a>
              </li>

              <li>
                <a href="{% url "manager:my-tasks" %}" class="dropdown-item">
                  <i class="fa-solid fa-list-check" style="color: #888888;"></i>
                  My Tasks
                </a>
              </li>
            </ul>
          </div>
        </div>
      </li>
    </ul>
  </div>
</header>

templates/includes/pagination.html
{% load query_transform %}

{% if is_paginated %}
  <nav>
    <ul class="pagination">
      <li class="page-item {% if not page_obj.has_previous %}disabled{% endif %}">
        <a
            href="?{% if page_obj.has_previous %}{% query_transform request page=page_obj.previous_page_number %}{% else %}{% query_transform request page=paginator.num_pages %}{% endif %}"
            class="page-link"
        >Previous</a>
      </li>

      {% if page_obj.has_previous %}
        <li class="page-item">
          <a
              href="?{% query_transform request page=page_obj.previous_page_number %}"
              class="page-link"
          >{{ page_obj.previous_page_number }}</a>
        </li>
      {% endif %}

      <li class="page-item active">
        <a
            href="?{% query_transform request page=page_obj.number %}"
            class="page-link"
        >{{ page_obj.number }}</a>
      </li>

      {% if page_obj.has_next %}
        <li class="page-item">
          <a
              href="?{% query_transform request page=page_obj.next_page_number %}"
              class="page-link"
          >{{ page_obj.next_page_number }}</a>
        </li>
      {% endif %}

      <li class="page-item {% if not page_obj.has_next %}disabled{% endif %}">
        <a
            href="?{% if page_obj.has_next %}{% query_transform request page=page_obj.next_page_number %}{% else %}{% query_transform request page=paginator.num_pages %}{% endif %}"
            class="page-link"
        >Next</a>
      </li>
    </ul>
  </nav>
{% endif %}

templates/includes/scripts.html
{% load static %}

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>
<script src="{% static 'assets/js/vendor-all.min.js' %}"></script>
<script src="{% static 'assets/plugins/bootstrap/js/bootstrap.min.js' %}"></script>
<script src="{% static 'assets/js/pcoded.min.js' %}"></script>
<script src="{% static 'assets/js/dark-mode.js' %}"></script>

templates/includes/sidebar.html
{% load static %}

<nav class="pcoded-navbar">
  <div class="navbar-wrapper">
    <div class="navbar-brand header-logo">
      <a href="{% url 'manager:index' %}" class="b-brand">
        <i class="fa-solid fa-list-check" style="color: #63E6BE;"></i>

        <span class="b-title">Task Manager</span>
      </a>

      <a class="mobile-menu" id="mobile-collapse" href="javascript:">
        <span></span>
      </a>
    </div>

    <div class="navbar-content scroll-div">
      <ul class="nav pcoded-inner-navbar">
        <li class="nav-item pcoded-menu-caption">
          <label>Navigation</label>
        </li>

        <li class="nav-item {% if 'index' in segment %}active{% endif %}">
          <a href="{% url 'manager:index' %}" class="nav-link ">
            <span class="pcoded-micon">
              <i class="fa-solid fa-house" style="color: #a9b7d0;"></i>
            </span>

            <span class="pcoded-mtext">Dashboard</span>
          </a>
        </li>

        <li class="nav-item {% if 'projects' in segment %}active{% endif %}">
          <a href="{% url "manager:project-list" %}" class="nav-link ">
            <span class="pcoded-micon">
              <i class="fa-solid fa-project-diagram" style="color: #a9b7d0;"></i>
            </span>

            <span class="pcoded-mtext">Projects</span>
          </a>
        </li>

        <li class="nav-item {% if 'teams' in segment %}active{% endif %}">
          <a href="{% url "manager:team-list" %}" class="nav-link ">
            <span class="pcoded-micon">
              <i class="fa-solid fa-people-group" style="color: #a9b7d0;"></i>
            </span>

            <span class="pcoded-mtext">Teams</span>
          </a>
        </li>

        <li class="nav-item {% if 'workers' in segment %}active{% endif %}">
          <a href="{% url "manager:worker-list" %}" class="nav-link ">
            <span class="pcoded-micon">
              <i class="fa-solid fa-user" style="color: #a9b7d0;"></i>
            </span>

            <span class="pcoded-mtext">Workers</span>
          </a>
        </li>
      </ul>
    </div>
  </div>
</nav>